# --- Install dependencies & build ---
FROM node:22.12.0-alpine AS builder
WORKDIR /app

# Copy package files and monorepo config
COPY package*.json turbo.json ./
 
COPY apps ./apps
COPY packages ./packages

# Install all dependencies
RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev"]
